name: Build and Release Haraka desktop

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    name: Build GUI for Windows
    steps:
      - name: Checkout GUI repo
        uses: actions/checkout@v4
      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Download Haraka CLI binary
        id: download_cli
        run: |
          $cliRepo="AhmedCharfeddine/Haraka"
          $apiUrl = "https://api.github.com/repos/$cliRepo/releases/latest"
          $headers = @{ "User-Agent" = "github-action" }
          $response = Invoke-RestMethod -Uri $apiUrl -Headers $headers
          $asset = $response.assets | Where-Object { $_.name -imatch "^Haraka_.*windows_amd64\.tar\.gz$" }
          if (-not $asset) {
            Write-Error "❌ Could not find a matching Haraka CLI archive in the latest release."
            exit 1
          }
          New-Item -ItemType Directory -Path bin -Force | Out-Null
          $archivePath = "bin\haraka.tar.gz"
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $archivePath
          tar -xzf $archivePath -C bin
          Remove-Item $archivePath
      - name: Build Avalonia GUI
        run: dotnet publish Haraka-desktop.csproj -c Release -f net8.0-windows -r win-x64 -o publish
      - name: Download .NET Desktop Runtime Installer
        run: |
          $url = "https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.16/windowsdesktop-runtime-8.0.16-win-x64.exe"
          Invoke-WebRequest -Uri $url -OutFile "windowsdesktop-runtime-8.0.16-win-x64.exe"
      - name: Install Inno Setup
        run: choco install innosetup --no-progress
      - name: Build installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "publish-script.iss"
      - name: Upload Release Installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: Output/Haraka-installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
